<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <PublishTrimmed>false</PublishTrimmed>
    <InvariantGlobalization>false</InvariantGlobalization>
    <AssemblyName>Arssyut.UI</AssemblyName>
    <RootNamespace>Arssyut.UI</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(InternalAudioPreview)' == 'true'">
    <DefineConstants>$(DefineConstants);ARSSYUT_INTERNAL_AUDIO_PREVIEW</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.3" />
    <PackageReference Include="Lucide.Avalonia" Version="0.2.23" />
  </ItemGroup>

  <ItemGroup Condition="Exists('Native\arssyut_native_bridge.dll')">
    <None Remove="Native\arssyut_native_bridge.dll" />
    <EmbeddedResource
        Include="Native\arssyut_native_bridge.dll"
        LogicalName="Arssyut.Native.arssyut_native_bridge.dll" />
  </ItemGroup>

</Project>
